# Generated by Django 3.2.6 on 2021-08-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraiserProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fundraiser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_proposal', related_query_name='fundraiser_proposal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
