# Generated by Django 3.2.6 on 2021-08-09 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fundraiserproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiserproposal',
            name='fundraiser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_proposal', related_query_name='fundraiser_proposal', to=settings.AUTH_USER_MODEL),
        ),
    ]
