# Generated by Django 3.2.6 on 2021-08-08 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', related_query_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
