# Generated by Django 3.2.6 on 2021-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
