# Generated by Django 3.2.6 on 2021-08-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_fundraiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Top Up Amount'),
        ),
    ]
