# Generated by Django 3.2.6 on 2021-08-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
