# Generated by Django 3.2.6 on 2021-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount'),
        ),
    ]
