# Generated by Django 3.2.6 on 2021-08-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaign_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='withdraw_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Withdrawn Amount'),
        ),
    ]
