# Generated by Django 3.2.6 on 2021-08-10 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topuphistory',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='bank_account_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Number only')]),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Top Up Verified'),
        ),
    ]
