# Generated by Django 3.2.6 on 2021-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Top Up Amount'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
