# Generated by Django 3.2.6 on 2021-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20210810_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='password',
            field=models.CharField(max_length=8, null=True, verbose_name='Password User'),
        ),
    ]
