# Generated by Django 3.2.6 on 2021-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_donationhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawrequest',
            options={'ordering': ('-request_date',)},
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='verified',
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=25, verbose_name='Withdraw Status'),
        ),
    ]
